version: "3.1"
services:
  bookapp:
    image : ajitnk2006/bookapp
    depends_on :
      - mysqldb
    ports:
      - 8080:8080 

     

  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - type: volume
        source: my-datavolume
        target: /var/lib/mysql
volumes:
  my-datavolume: